// composables/useProjects.ts
const R2 = "https://assets.etheeratech.com";

export const useProjects = () => {
  return [
    {
      id: "gobekusa-project",
      title: "Shopify Dropshipping Store — US Market",
      desc: "A full-featured Shopify dropshipping store built for the US tile and natural stone market. Includes custom theme development, bulk product imports, SEO optimization, and a custom 'Buy Sample' feature built with Liquid and JavaScript.",
      link: "https://gobekusa.com",
      gif: `${R2}/images/projects/gobekusa/gobekusa-1.webp`,
      images: [
        `${R2}/images/projects/gobekusa/gobekusa-1.webp`,
        `${R2}/images/projects/gobekusa/gobekusa-2.webp`,
        `${R2}/images/projects/gobekusa/gobekusa-3.webp`,
      ],
      techStack: [
        "Shopify",
        "Liquid",
        "JavaScript",
        "Matrixify",
        "Judge.me",
        "Collective",
        "Cloudflare",
        "SEO",
      ],
    },
    {
      id: "mekmar-shopify",
      title: "Multilingual Shopify Store — Natural Stone Export",
      desc: "A full-featured multilingual Shopify store built for a Turkish natural stone export company. Includes Weglot multilingual setup with custom subdomain routing, bulk product imports via Matrixify, SEO audit, schema markup, and a Google Reviews widget powered by a Vercel serverless proxy.",
      link: "https://mekmar.com",
      gif: `${R2}/images/projects/mekmar/mekmar-shopify-1.webp`,
      images: [
        `${R2}/images/projects/mekmar/mekmar-shopify-1.webp`,
        `${R2}/images/projects/mekmar/mekmar-shopify-2.webp`,
        `${R2}/images/projects/mekmar/mekmar-shopify-3.webp`,
        `${R2}/images/projects/mekmar/mekmar-shopify-4.webp`,
        `${R2}/images/projects/mekmar/mekmar-shopify-5.webp`,
        `${R2}/images/projects/mekmar/mekmar-shopify-6.webp`,
        `${R2}/images/projects/mekmar/mekmar-shopify-7.webp`,
        `${R2}/images/projects/mekmar/mekmar-shopify-8.webp`,
        `${R2}/images/projects/mekmar/mekmar-shopify-9.webp`,
        `${R2}/images/projects/mekmar/mekmar-shopify-10.webp`,
        `${R2}/images/projects/mekmar/mekmar-shopify-11.webp`,
        `${R2}/images/projects/mekmar/mekmar-shopify-12.webp`,
        `${R2}/images/projects/mekmar/mekmar-shopify-13.webp`,
      ],
      techStack: [
        "Shopify",
        "Liquid",
        "Weglot",
        "Matrixify",
        "Judge.me",
        "Cloudflare",
        "Vercel",
        "SEO",
      ],
    },
    {
      id: "goz-mekmar",
      title: "Internal ERP Portal — Construction Company",
      desc: "A full-stack internal portal built for a construction company operating across multiple sites. Features real-time team communication via Socket.io, project & task management, document sharing, interactive dashboards with Chart.js, and role-based access control — all backed by a Python REST API and MS SQL Server.",
      link: null,
      gif: `${R2}/images/projects/goz/goz-1.webp`,
      images: [
        `${R2}/images/projects/goz/goz-1.webp`,
        `${R2}/images/projects/goz/goz-2.webp`,
        `${R2}/images/projects/goz/goz-3.webp`,
        `${R2}/images/projects/goz/goz-4.webp`,
        `${R2}/images/projects/goz/goz-5.webp`,
        `${R2}/images/projects/goz/goz-6.webp`,
        `${R2}/images/projects/goz/goz-7.webp`,
        `${R2}/images/projects/goz/goz-8.webp`,
        `${R2}/images/projects/goz/goz-9.webp`,
      ],
      techStack: [
        "Nuxt 3",
        "Vue 3",
        "Pinia",
        "Socket.io",
        "Python",
        "FastAPI",
        "MS SQL Server",
        "Chart.js",
        "PrimeVue",
        "JWT Auth",
      ],
    },
    {
      id: "emregeldi-project",
      title: "Law Firm Website — Av. Emre Geldi",
      desc: "A professional corporate website built on Shopify for a Denizli-based law firm. Features 14 practice area pages with detailed legal content, a categorized legal articles blog, contact form with subject selection, Google Maps integration, WhatsApp support widget, KVKK/privacy compliance pages, and links to official Turkish legal institutions.",
      link: "https://emregeldi.av.tr",
      gif: `${R2}/images/projects/emregeldi/emregeldi-1.webp`,
      images: [
        `${R2}/images/projects/emregeldi/emregeldi-1.webp`,
        `${R2}/images/projects/emregeldi/emregeldi-2.webp`,
        `${R2}/images/projects/emregeldi/emregeldi-3.webp`,
        `${R2}/images/projects/emregeldi/emregeldi-4.webp`,
      ],
      techStack: [
        "Shopify",
        "Liquid",
        "Custom Pages",
        "SEO",
        "WhatsApp Integration",
        "Google Maps",
        "KVKK Compliance",
      ],
    },
    {
      id: "pandora-project",
      title: "Cleaning Services Website — Pandora Temizlik",
      desc: "A modern service website built with Nuxt 3 for a professional cleaning company in Denizli. Features service pages for sofa, carpet, mattress and curtain cleaning, a pricing page, photo gallery, contact & appointment form, WhatsApp integration, local SEO with district-based landing pages (Merkezefendi, Pamukkale, Kınıklı), and Vercel image optimization.",
      link: "https://denizlipandoratemizlik.com.tr",
      gif: `${R2}/images/projects/pandora/pandora-1.webp`,
      images: [
        `${R2}/images/projects/pandora/pandora-1.webp`,
        `${R2}/images/projects/pandora/pandora-2.webp`,
        `${R2}/images/projects/pandora/pandora-3.webp`,
        `${R2}/images/projects/pandora/pandora-4.webp`,
        `${R2}/images/projects/pandora/pandora-5.webp`,
      ],
      techStack: [
        "Nuxt 3",
        "Vue 3",
        "TailwindCSS",
        "Vercel",
        "Local SEO",
        "WhatsApp API",
        "Schema Markup",
      ],
    },
    {
      id: "velnora-project",
      title: "Multilingual Dropshipping Store — VelnoraUSA",
      desc: "A multilingual multi-category Shopify dropshipping store built for the US market, covering pet supplies, home decor, lighting, and more. Integrated with DSers for AliExpress product sourcing and order automation, Weglot for multilingual storefront, and custom theme configuration with SEO-optimized collection and product pages.",
      link: "https://velnorausa.com",
      gif: `${R2}/images/projects/velnora/velnora-1.webp`,
      images: [
        `${R2}/images/projects/velnora/velnora-1.webp`,
        `${R2}/images/projects/velnora/velnora-2.webp`,
        `${R2}/images/projects/velnora/velnora-3.webp`,
        `${R2}/images/projects/velnora/velnora-4.webp`,
        `${R2}/images/projects/velnora/velnora-5.webp`,
      ],
      techStack: [
        "Shopify",
        "Liquid",
        "DSers",
        "AliExpress",
        "Weglot",
        "Matrixify",
        "SEO",
        "Theme Customization",
      ],
    },
  ];
};
